# Layer Onboarding Project
# Kaggle Public Datasets Used: https://www.kaggle.com/olistbr/brazilian-ecommerce

# Project configuration file
# For more information: https://docs.beta.layer.co/docs/projects/project-yml

apiVersion: 1

# Name of your project
name: "Onboarding_churn_project"
